import axios from 'axios'
import Head from 'next/head'
import React, { useState } from 'react'
import { IoCall } from 'react-icons/io5'
import { IoMdMail } from 'react-icons/io'
import Alert from '@/components/UI/Alert'
import { FaMapMarkerAlt, FaFacebookF, FaLinkedin, FaGithub, FaTwitter, FaLeaf } from 'react-icons/fa' 

const Contact = () => {

    const [values, setValues] = useState({
        name: '',
        email: '',
        message: ''
    })
    const [isSuccess, setIsSuccess] = useState(false)

    const handleChange = (e) => {
        const { id, value } = e.target
        setValues({
            ...values,
            [id]: value
        }) 
    }
    const handleSubmit = (e) => {
        e.preventDefault()
        if(values.name.trim() && values.email.trim() && values.message.trim()) {
            const formatMessage = {
                name: values.name.trim(),
                email: values.email.trim(),
                message: values.message.replaceAll('\n', '').trim(),
            }
            const confirm = window.confirm('Are you sure want to send a message ?')
            if(confirm) {
                axios.post(`${process.env.NEXT_PUBLIC_URL}/api/messages`, {
                    data: formatMessage
                }).then(() => {
                    setIsSuccess(true)
                    setValues({
                        name: '',
                        email: '',
                        message: ''
                    })
                }) 
            }
        } else {
            alert('Please fill the field input!')
        }
    }

    return (
        <section className='my-10 text-white'>
            <Head>
                <title>Contact Page | NextStrapi</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {isSuccess && <Alert handleClose={() => setIsSuccess(false)} title='Your message has been sended'/>}
            <div className='text-center'>
                <h1 className='text-3xl font-medium'>Contact Us</h1>
                <p className='mt-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit, culpa!</p>
            </div>
            <div className='flex flex-col-reverse md:flex-row md:space-x-5 mt-16'>
                <div className='flex flex-col justify-between h-[400px] md:h-auto w-auto md:w-[350px] lg:w-[500px] bg-white rounded-md text-gray-800 p-5'>
                    <div>
                        <h2 className='text-xl font-medium mb-3'>Contact Information</h2>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis quia iste dolor perferendis consectetur odit et labore, aut debitis tempora.</p>
                        <div className="flex flex-col space-y-3 mt-5">
                            <div className='flex items-center space-x-4'>
                                <IoCall/>
                                <p>+6285848128298</p>
                            </div>
                            <div className='flex items-center space-x-4'>
                                <IoMdMail/>
                                <p>permanahendra2308@gmail.com</p>
                            </div>
                            <div className='flex items-center space-x-4'>
                                <FaMapMarkerAlt/>
                                <p>Purbalingga, Indonesia</p>
                            </div>
                        </div>
                    </div>
                    <div className='flex items-center justify-end space-x-5'>
                        <FaFacebookF className='cursor-pointer text-gray-700 hover:text-gray-800'/>
                        <FaGithub className='cursor-pointer text-gray-700 hover:text-gray-800'/>
                        <FaLinkedin className='cursor-pointer text-gray-700 hover:text-gray-800'/>
                        <FaTwitter className='cursor-pointer text-gray-700 hover:text-gray-800'/>
                    </div>
                </div>

                <div className='flex-grow rounded-md mb-10 md:mb-0 '>
                    <h2 className='text-center text-xl mb-3'>Send Message</h2>
                    <form onSubmit={handleSubmit}>
                        <div className='input-control'>
                            <label htmlFor="name" className='text-lg'>Name</label>
                            <input 
                                type="text" 
                                id='name' 
                                placeholder='Type your name' 
                                className='input-message'
                                value={values.name}
                                onChange={handleChange}/>
                        </div>
                        <div className='input-control'>
                            <label htmlFor="email" className='text-lg'>Email</label>
                            <input 
                                type="email" 
                                id='email' 
                                placeholder='Type your email' 
                                className='input-message'
                                value={values.email}
                                onChange={handleChange}/>
                        </div>
                        <div className='input-control'>
                            <label htmlFor="message" className='text-lg'>Message</label>
                            <textarea 
                                rows={4} 
                                id='message' 
                                placeholder='Type your message' 
                                className='input-message'
                                value={values.message}
                                onChange={handleChange}/>
                        </div>
                        <button className='p-2 bg-blue-600 hover:bg-blue-700 transition duration-200 rounded text-white cursor-pointer w-full' type="submit">Send Message</button>
                    </form>
                </div>
            </div>
        </section>
    )
}

export default Contact
